name: no_comment_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.5
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  stroke_text: ^1.0.0
  location: ^8.0.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  supabase_flutter: ^2.0.0
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
